"""Renders build_report_data()'s output to a multi-page PDF using fpdf2.

Pure presentation layer -- no calculation happens here. Every number comes
from the report_data dict already assembled by report_generator.py.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from fpdf import FPDF

_NAVY = (41, 37, 31)
_SLATE = (92, 85, 76)
_LIGHT = (245, 243, 239)
_WHITE = (255, 255, 255)
_ACCENT = (31, 138, 127)

_SEVERITY_RGB = {
    "Critical": (185, 28, 28),
    "High": (217, 119, 6),
    "Medium": (202, 138, 4),
    "Low": (101, 163, 13),
    "None": (22, 163, 74),
}


class _ReportPDF(FPDF):
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*_SLATE)
        self.cell(140, 8, "Data Quality Assessment Report", align="L")
        self.cell(50, 8, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*_LIGHT)
        self.line(10, 16, 200, 16)
        self.ln(4)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*_SLATE)
        self.cell(0, 8, "Generated by Data Quality Engine -- Phase 1 (deterministic, rule-based, no AI)", align="C")


def _severity_badge(pdf: FPDF, severity: str):
    rgb = _SEVERITY_RGB.get(severity, (100, 100, 100))
    pdf.set_fill_color(*rgb)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 8)
    w = pdf.get_string_width(severity) + 6
    pdf.cell(w, 6, severity, fill=True, align="C")
    pdf.set_text_color(0, 0, 0)


def _section_title(pdf: FPDF, title: str):
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*_NAVY)
    pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(*_ACCENT)
    pdf.set_line_width(0.8)
    pdf.line(10, pdf.get_y(), 40, pdf.get_y())
    pdf.ln(4)
    pdf.set_text_color(0, 0, 0)


def _kv_row(pdf: FPDF, label: str, value: str, label_w: int = 55):
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*_SLATE)
    pdf.cell(label_w, 7, label)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")


def _draw_check_icon(pdf: FPDF, cx: float, cy: float, r: float = 12):
    """A simple checkmark-in-circle, drawn with native fpdf2 shapes (no image/font dependency)."""
    pdf.set_draw_color(74, 222, 128)
    pdf.set_line_width(1.2)
    pdf.ellipse(cx - r, cy - r, r * 2, r * 2, style="D")
    pdf.set_line_width(1.6)
    pdf.line(cx - r * 0.45, cy, cx - r * 0.1, cy + r * 0.4)
    pdf.line(cx - r * 0.1, cy + r * 0.4, cx + r * 0.5, cy - r * 0.35)


def _cover_page(pdf: FPDF, data: dict[str, Any]):
    pdf.add_page()
    pdf.set_fill_color(*_NAVY)
    pdf.rect(0, 0, 210, 297, style="F")

    _draw_check_icon(pdf, 105, 45)

    pdf.set_y(60)
    pdf.set_text_color(*_WHITE)
    pdf.set_font("Helvetica", "B", 26)
    pdf.cell(0, 14, "Data Quality Assessment Report", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 13)
    pdf.set_text_color(200, 210, 225)
    pdf.cell(0, 10, data["meta"]["filename"], align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Sheet: {data['meta']['sheet_name']}", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_y(140)
    score = data["score"]["overall"]
    score_text = f"{score:.1f}" if score is not None else "N/A"
    pdf.set_font("Helvetica", "B", 54)
    pdf.set_text_color(*_WHITE)
    pdf.cell(0, 30, score_text, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(200, 210, 225)
    pdf.cell(0, 8, "Overall Quality Score  /  100", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(6)
    rgb = _SEVERITY_RGB.get(
        {"Excellent": "None", "Good": "Low", "Fair": "Medium", "Poor": "Critical", "Unrated": "High"}.get(
            data["score"]["rating"], "Medium"
        ),
        (100, 100, 100),
    )
    pdf.set_x(75)
    pdf.set_fill_color(*rgb)
    pdf.set_font("Helvetica", "B", 12)
    label = data["score"]["rating"]
    w = pdf.get_string_width(label) + 16
    pdf.cell(w, 10, label, fill=True, align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_y(230)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(190, 200, 220)
    meta = data["meta"]
    pdf.cell(0, 6, f"Processing Date: {meta['generated_at']}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Engine Version: {meta['engine_version']}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0, 6, f"Execution Time: {meta['processing_time_seconds']}s", align="C", new_x="LMARGIN", new_y="NEXT"
    )
    pdf.cell(0, 6, "Generated By: Data Quality Engine (Phase 1)", align="C", new_x="LMARGIN", new_y="NEXT")


def _executive_summary_page(pdf: FPDF, data: dict[str, Any]):
    pdf.add_page()
    _section_title(pdf, "Executive Summary")

    ov = data["overview"]
    sc = data["score"]
    _kv_row(pdf, "Dataset:", data["meta"]["filename"])
    _kv_row(pdf, "Rows / Columns:", f"{ov['rows']:,} rows x {ov['columns']} columns")
    _kv_row(pdf, "Checks Executed:", str(ov["checks_executed"]))
    _kv_row(
        pdf,
        "Overall Quality Score:",
        f"{sc['overall']:.1f} / 100  ({sc['rating']})" if sc["overall"] is not None else "N/A",
    )
    if sc["dimensions_excluded"]:
        _kv_row(pdf, "Dimensions Excluded:", ", ".join(sc["dimensions_excluded"]))
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*_SEVERITY_RGB["Critical"])
    pdf.cell(0, 8, "Critical Findings", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(0, 0, 0)
    if data["executive_summary"]["critical_findings"]:
        for f in data["executive_summary"]["critical_findings"]:
            pdf.multi_cell(0, 6, f"-  {f}", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.multi_cell(0, 6, "None identified.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*_SEVERITY_RGB["None"])
    pdf.cell(0, 8, "Positive Findings", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(0, 0, 0)
    if data["executive_summary"]["positive_findings"]:
        for f in data["executive_summary"]["positive_findings"]:
            pdf.multi_cell(0, 6, f"-  {f}", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.multi_cell(0, 6, "None -- see check sections for detail.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*_NAVY)
    pdf.cell(0, 8, "Data Readiness", new_x="LMARGIN", new_y="NEXT")
    rgb = _SEVERITY_RGB.get(
        {
            "Ready": "None",
            "Ready with Minor Cleaning": "Low",
            "Ready with Moderate Cleaning": "Medium",
            "Not Recommended": "Critical",
        }.get(sc["readiness"], "Medium"),
        (100, 100, 100),
    )
    pdf.set_fill_color(*rgb)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 11)
    w = pdf.get_string_width(sc["readiness"]) + 10
    pdf.cell(w, 9, sc["readiness"], fill=True, align="C")
    pdf.set_text_color(0, 0, 0)


def _business_impact_page(pdf: FPDF, data: dict[str, Any]):
    pdf.add_page()
    _section_title(pdf, "Business Impact & Risk Summary")

    pdf.set_font("Helvetica", "", 9)
    for name, summary in data["checks"].items():
        if summary["severity"] == "None":
            continue
        pdf.set_font("Helvetica", "B", 10.5)
        pdf.cell(0, 8, summary["display_name"], new_x="LMARGIN", new_y="NEXT")
        _severity_badge(pdf, summary["severity"])
        pdf.ln(9)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5.5, f"Business Impact: {summary['business_impact']}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    if data["pii"]["columns_with_pii"] > 0:
        pdf.set_font("Helvetica", "B", 10.5)
        pdf.cell(0, 8, "PII Exposure", new_x="LMARGIN", new_y="NEXT")
        _severity_badge(pdf, "Critical")
        pdf.ln(9)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5.5, "Business Impact: Privacy and compliance risk if this data is shared unmasked.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)


def _dataset_overview_page(pdf: FPDF, data: dict[str, Any]):
    pdf.add_page()
    _section_title(pdf, "Dataset Overview")
    ov = data["overview"]
    _kv_row(pdf, "Rows:", f"{ov['rows']:,}")
    _kv_row(pdf, "Columns:", str(ov["columns"]))
    _kv_row(pdf, "Header Row:", str(ov["header_row"]))
    _kv_row(pdf, "Processing Time:", f"{data['meta']['processing_time_seconds']}s")
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Column Classification", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    role_labels = {
        "measurement": "Measurement Columns",
        "identifier": "Identifier Columns",
        "pii": "PII Columns",
        "free_text": "Free-Text Columns",
        "categorical": "Categorical Columns",
        "date": "Date Columns",
    }
    for role, label in role_labels.items():
        count = ov["role_counts"].get(role, 0)
        _kv_row(pdf, f"{label}:", str(count), label_w=70)


def _draw_dimension_bar_chart(pdf: FPDF, dims: dict[str, Any], x0: float, y0: float, width: float):
    """Native fpdf2 horizontal bar chart -- no matplotlib dependency needed."""
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*_NAVY)
    pdf.set_xy(x0, y0)
    pdf.cell(0, 8, "Dimension Scores at a Glance", new_x="LMARGIN", new_y="NEXT")
    y = y0 + 10
    label_w = 42
    bar_max_w = width - label_w - 14
    row_h = 8.5
    for dim, info in dims.items():
        score = info.get("score") if info.get("available") else 0
        score = score or 0
        color = (22, 163, 74) if score >= 90 else (101, 163, 13) if score >= 75 else (202, 138, 4) if score >= 55 else (185, 28, 28)
        pdf.set_xy(x0, y)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(*_SLATE)
        pdf.cell(label_w, row_h, dim.replace("_", " ").title())
        bar_x = x0 + label_w
        pdf.set_fill_color(*_LIGHT)
        pdf.rect(bar_x, y + 1.5, bar_max_w, 5, style="F")
        fill_w = bar_max_w * (score / 100.0)
        if fill_w > 0:
            pdf.set_fill_color(*color)
            pdf.rect(bar_x, y + 1.5, fill_w, 5, style="F")
        pdf.set_xy(bar_x + bar_max_w + 3, y)
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_text_color(*_NAVY)
        pdf.cell(10, row_h, f"{score:.0f}")
        y += row_h
    return y


def _draw_privacy_risk_bar(pdf: FPDF, pr: dict[str, Any], x0: float, y0: float, width: float):
    pii_cols = pr.get("columns_with_pii", 0)
    total_cols = max(pr.get("total_columns", 0), 1)
    clean_cols = max(total_cols - pii_cols, 0)
    risk_color = {"high": (185, 28, 28), "medium": (202, 138, 4), "low": (101, 163, 13), "none": (22, 163, 74)}.get(
        pr.get("risk_level", "none"), (100, 100, 100)
    )
    bar_h = 10
    pdf.set_xy(x0, y0)
    pdf.set_fill_color(*_LIGHT)
    pdf.rect(x0, y0, width, bar_h, style="F")
    pii_w = width * (pii_cols / total_cols)
    if pii_w > 0:
        pdf.set_fill_color(*risk_color)
        pdf.rect(x0, y0, pii_w, bar_h, style="F")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*_SLATE)
    pdf.set_xy(x0, y0 + bar_h + 2)
    pdf.cell(width, 5, f"{pii_cols} column(s) with PII  vs.  {clean_cols} clean column(s)  (of {total_cols} total)")


def _score_dashboard_page(pdf: FPDF, data: dict[str, Any]):
    pdf.add_page()
    _section_title(pdf, "Data Quality Dashboard")

    dims = data["score"]["dimension_scores"]
    col_w = 63
    x0, y0 = 10, pdf.get_y()
    i = 0
    for dim, info in dims.items():
        col = i % 3
        row = i // 3
        x = x0 + col * col_w
        y = y0 + row * 34
        pdf.set_xy(x, y)
        pdf.set_fill_color(*_LIGHT)
        pdf.rect(x, y, col_w - 4, 30, style="F")
        pdf.set_xy(x + 3, y + 3)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_SLATE)
        pdf.cell(col_w - 10, 5, dim.replace("_", " ").title())
        pdf.set_xy(x + 3, y + 10)
        score_val = info.get("score")
        pdf.set_font("Helvetica", "B", 16)
        if score_val is not None:
            pdf.set_text_color(*_NAVY)
        else:
            pdf.set_text_color(*_SLATE)
        pdf.cell(col_w - 10, 10, f"{score_val:.0f}" if score_val is not None else "N/A")
        pdf.set_xy(x + 3, y + 22)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*_SLATE)
        pdf.cell(col_w - 10, 5, f"weight {info.get('weight', 0):.0%}  |  {'assessed' if info.get('available') else 'skipped'}")
        i += 1
    y_after_cards = y0 + ((i - 1) // 3 + 1) * 34 + 10

    y_after_chart = _draw_dimension_bar_chart(pdf, dims, 10, y_after_cards, 190)
    pdf.set_y(y_after_chart + 8)

    pr = data["privacy_risk"]
    if pr:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*_NAVY)
        pdf.cell(0, 8, "Privacy Risk (separate from score above)", new_x="LMARGIN", new_y="NEXT")
        rgb = {"high": (185, 28, 28), "medium": (202, 138, 4), "low": (101, 163, 13), "none": (22, 163, 74)}.get(
            pr.get("risk_level", "none"), (100, 100, 100)
        )
        pdf.set_fill_color(*rgb)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 10)
        label = pr.get("risk_level", "none").upper()
        w = pdf.get_string_width(label) + 10
        pdf.cell(w, 8, label, fill=True, align="C")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(12)
        _draw_privacy_risk_bar(pdf, pr, 10, pdf.get_y(), 190)
        pdf.ln(20)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(
            0,
            5.5,
            f"Types found: {', '.join(pr.get('pii_types_found', [])) or 'none'}",
            new_x="LMARGIN",
            new_y="NEXT",
        )


def _check_section(pdf: FPDF, summary: dict[str, Any]):
    pdf.add_page()
    _section_title(pdf, summary["display_name"])
    _severity_badge(pdf, summary["severity"])
    pdf.ln(10)

    _kv_row(pdf, "Columns Checked:", str(summary["columns_checked"]))
    _kv_row(pdf, "Columns with Issues:", str(summary["columns_with_issues"]))
    _kv_row(pdf, "Total Issues Found:", str(summary["total_issues_found"]))
    if summary["affected_columns"]:
        _kv_row(pdf, "Affected Columns:", ", ".join(summary["affected_columns"][:15]))
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 10.5)
    pdf.cell(0, 7, "Business Impact", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.multi_cell(0, 5.5, summary["business_impact"], new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 10.5)
    pdf.cell(0, 7, "Recommendation", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.multi_cell(0, 5.5, summary["recommendation"], new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    if summary["sample_findings"]:
        pdf.set_font("Helvetica", "B", 10.5)
        pdf.cell(0, 7, "Sample Findings", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 8.5)
        for f in summary["sample_findings"]:
            col = f.get("column", "-")
            issues = f.get("issues_found", "-")
            extra = {k: v for k, v in f.items() if k not in ("column", "issues_found")}
            extra_str = "; ".join(f"{k}={v}" for k, v in extra.items())
            pdf.multi_cell(0, 5, f"-  {col}: {issues} issue(s)  {extra_str}"[:250], new_x="LMARGIN", new_y="NEXT")


def _column_matrix_page(pdf: FPDF, data: dict[str, Any]):
    matrix = data["column_matrix"]
    if not matrix:
        return
    pdf.add_page()
    _section_title(pdf, "Column Quality Matrix")

    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*_NAVY)
    pdf.set_text_color(255, 255, 255)
    headers = [("Column", 45), ("Role", 25), ("Score", 15), ("Issues", 15), ("Severity", 20), ("Recommendation", 70)]
    for h, w in headers:
        pdf.cell(w, 7, h, fill=True, border=1)
    pdf.ln()

    pdf.set_font("Helvetica", "", 7.5)
    pdf.set_text_color(0, 0, 0)
    for idx, row in enumerate(matrix[:40]):
        if pdf.get_y() > 275:
            pdf.add_page()
        if idx % 2 == 1:
            pdf.set_fill_color(248, 250, 252)
            row_fill = True
        else:
            pdf.set_fill_color(255, 255, 255)
            row_fill = True
        pdf.cell(45, 6, row["column"][:28], border=1, fill=row_fill)
        pdf.cell(25, 6, row["role"], border=1, fill=row_fill)
        pdf.cell(15, 6, f"{row['quality_score']:.0f}", border=1, fill=row_fill)
        pdf.cell(15, 6, str(row["issues_found"]), border=1, fill=row_fill)
        rgb = _SEVERITY_RGB.get(row["severity"], (100, 100, 100))
        pdf.set_fill_color(*rgb)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(20, 6, row["severity"], border=1, fill=True, align="C")
        pdf.set_text_color(0, 0, 0)
        pdf.set_fill_color(248, 250, 252) if idx % 2 == 1 else pdf.set_fill_color(255, 255, 255)
        pdf.cell(70, 6, row["recommendation"][:55], border=1, fill=True)
        pdf.ln()


def _top_issues_page(pdf: FPDF, data: dict[str, Any]):
    if not data["top_issues"]:
        return
    pdf.add_page()
    _section_title(pdf, "Top Critical Issues")
    for i, issue in enumerate(data["top_issues"], 1):
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(8, 8, f"{i}.")
        pdf.cell(0, 8, f"{issue['issue']} -- {issue['column']}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_x(18)
        _severity_badge(pdf, issue["severity"])
        pdf.ln(9)
        pdf.set_x(18)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.multi_cell(0, 5, f"Impact: {issue['impact']}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_x(18)
        pdf.multi_cell(0, 5, f"Action: {issue['action']}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)


def _appendix_page(pdf: FPDF, data: dict[str, Any]):
    pdf.add_page()
    _section_title(pdf, "Appendix")
    meta = data["meta"]
    _kv_row(pdf, "Execution Time:", f"{meta['processing_time_seconds']}s")
    _kv_row(pdf, "Engine Version:", meta["engine_version"])
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 10.5)
    pdf.cell(0, 7, "Scoring Formula", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(
        0,
        5.5,
        "Each dimension score = 100 x (passed checks / total non-error checks) for that dimension. "
        "Composite score = weighted average across scorable dimensions only (weights re-normalized "
        "when a dimension has no results). Privacy Risk is calculated and reported separately and is "
        "never subtracted from the composite score.",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 10.5)
    pdf.cell(0, 7, "Quality Dimensions", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    for dim, info in data["score"]["dimension_scores"].items():
        pdf.multi_cell(0, 5.5, f"-  {dim.replace('_', ' ').title()}  (weight: {info.get('weight', 0):.0%})", new_x="LMARGIN", new_y="NEXT")


def generate_pdf_report(report_data: dict[str, Any], output_path: str) -> str:
    """Renders report_data (from report_generator.build_report_data) to a PDF file."""
    pdf = _ReportPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)

    _cover_page(pdf, report_data)
    _executive_summary_page(pdf, report_data)
    _business_impact_page(pdf, report_data)
    _dataset_overview_page(pdf, report_data)
    _score_dashboard_page(pdf, report_data)
    for summary in report_data["checks"].values():
        _check_section(pdf, summary)
    _column_matrix_page(pdf, report_data)
    _top_issues_page(pdf, report_data)
    _appendix_page(pdf, report_data)

    output_path = str(output_path)
    pdf.output(output_path)
    return output_path